# Generated by Django 5.2.6 on 2025-09-10 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='shift_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='shift_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.TextField(default='Mon-Fri', help_text='e.g., Mon-Fri'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('DO', 'DO'), ('DM', 'DM'), ('PhD', 'PhD'), ('MBChB', 'MBChB')], default='MBBS', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('General Physician', 'General Physician'), ('Pediatrician', 'Pediatrician'), ('Orthopedic', 'Orthopedic'), ('Psychiatrist', 'Psychiatrist'), ('Gynecologist', 'Gynecologist'), ('ENT Specialist', 'ENT Specialist'), ('Radiologist', 'Radiologist')], max_length=100),
        ),
    ]
