# Generated by Django 5.2.6 on 2025-09-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
