# Generated by Django 5.2.4 on 2025-09-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.TextField(default='Dr.', max_length=200),
        ),
    ]
