# Generated by Django 5.2.4 on 2025-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_specialization',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(max_length=100),
        ),
    ]
