# Generated by Django 5.2.4 on 2025-09-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_name',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor_specialization',
        ),
    ]
