# Generated by Django 5.2.4 on 2025-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_rename_doctor_name_patient_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_specialization',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
