# Generated by Django 4.2.7 on 2026-01-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_patient_doctor_patient_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Pending', max_length=20),
        ),
    ]
