# Generated by Django 5.2.6 on 2025-09-10 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shift_end',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('Technician', 'Technician'), ('Receptionist', 'Receptionist'), ('Accountant', 'Accountant'), ('Cleaner', 'Cleaner'), ('Pharmacist', 'Pharmacist'), ('Administrator', 'Administrator')], default='Nurse', max_length=50),
        ),
    ]
